spring:
  datasource:
    url: jdbc:h2:file:./data/waitlistdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or "create" to reset every time
    show-sql: true       # To see SQL queries in logs