spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none    # Prevent JPA from auto-creating tables
    show-sql: true       # Optional: Print SQL statements during tests
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init-mode: always     # Ensures SQL scripts run at startup

